### ISSUE TITLE
Release 0.3.0?

### ISSUE THREAD

**Issue by michaeldauria** [bsm/poseidon_cluster#14]
I am working on a project (promiscuous-io/promiscuous) that I am moving over to Kafka, but it needs to have this gem as well as poseidon in its gemspec and the version released (0.1.1) is incompatible with poseidon 0.0.5.

Could you please release a version that is compatible with 0.0.5?

**Comment by lucasrodcosta** [comment]
+1.
Same problem here.

Would be great a release compatible with poseidon 0.0.5.

**Comment by richardwan** [comment]
me too please

**Comment by inf0rmer** [comment]
+1, would love a new release as well.

**Comment by tarcieri** [comment]
+1

**Comment by tarcieri** [comment]
If there's not going to be any forward movement on this gem, I think I'd like to swallow up its guts and fold them into my gem Turbine:

https://github.com/tarcieri/turbine

Turbine provides a performance-oriented multi-threaded (thread pool-backed) stream processor interface for Kafka queues and is presently using poseidon_cluster for implementing consumer groups / checkpointing.

I've run into some various API issues and apparent thread-(un)safety issues with poseidon_cluster that I'd like to shore up, and I feel like integrating this gem into Turbine is probably the best path forward.

I will of course give credit where it is due. The license given in the poseidon_cluster README appears to be MIT, which is the same license Turbine is under.

cc @michaeldauria @lucasrodcosta @richardwan @inf0rmer @dim @kssminus @bjhaid @davideauee

**Comment by dim** [comment]
Hey all, apologies for the delayed response, but we've been a tad busy in the past few weeks (to say it nicely). Given that it might take a while for us to get back to this project, I am happy to hand over the development to someone else. This lib worked fine for us, but it really needs some TLC. While working on https://github.com/bsm/sarama-cluster, we noticed some additional pitfalls that are not covered in the latest master (yet). 

Please let me know what you prefer, I am happy to give keen participants write access to this repo and transfer ownership of this gem.

PS: The next version of Kafka (0.8.3) is due to be released next month. Its goal is to simplify client design by assuming the ownership of the rebalancing process - https://cwiki.apache.org/confluence/display/KAFKA/Kafka+0.9+Consumer+Rewrite+Design

**Comment by dim** [comment]
In the meantime, I don't want to let you waiting, so here it is:https://rubygems.org/gems/poseidon_cluster/versions/0.3.0
